AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A service to perform actions on online content.

Globals:
  Function:
    Timeout: 180

Parameters:
  OpenAIApiKey:
    Type: String
    Description: OpenAI API key for content processing
    NoEcho: true
  DomainName:
    Type: String
    Description: Domain where the API can be accessed
  CertificateArn:
    Type: String
    Description: ARN of the SSL cert in ACM
  HostedZoneId:
    Type: String
    Description: Id of the hosted zone in Route53

Resources:
  SummaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.summary.handler
      Runtime: python3.12
      Tracing: Active
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref SummaryTable
          OPENAI_API_KEY_SSM_NAME: openaiApiKey
          AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SummaryTable
        - Statement:
            - Sid: SSMParameterRead
              Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
              Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/openaiApiKey
        - AWSXrayWriteOnlyAccess
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ContentApi
            Path: /summary
            Method: get

  SummaryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Summary
      AttributeDefinitions:
        - AttributeName: url
          AttributeType: S
      KeySchema:
        - AttributeName: url
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  CriticalThinkingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.critical_thinking.handler
      Runtime: python3.12
      Tracing: Active
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref CriticalThinkingTable
          OPENAI_API_KEY_SSM_NAME: openaiApiKey
          AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CriticalThinkingTable
        - Statement:
            - Sid: SSMParameterRead
              Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
              Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/openaiApiKey
        - AWSXrayWriteOnlyAccess      
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ContentApi
            Path: /critical-thinking
            Method: get

  CriticalThinkingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CriticalThinking
      AttributeDefinitions:
        - AttributeName: url
          AttributeType: S
      KeySchema:
        - AttributeName: url
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ContentApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowOrigins:
          - "*"
      Domain:
        DomainName: !Ref DomainName
        CertificateArn: !Ref CertificateArn
        Route53:
          HostedZoneId: !Ref HostedZoneId

  OpenAIKey:
    Type: AWS::SSM::Parameter
    Properties:
      Name: openaiApiKey
      Type: String
      Value: !Ref OpenAIApiKey
      Description: OpenAI API key for content summarization

Outputs:
  SummaryApiUrl:
    Description: "URL of the HTTP API endpoint for the summary service"
    Value: !Sub "https://${ContentApi}.execute-api.${AWS::Region}.amazonaws.com/prod/summary"
  CriticalThinkingApiUrl:
    Description: "URL of the HTTP API endpoint for the critical thinking service"
    Value: !Sub "https://${ContentApi}.execute-api.${AWS::Region}.amazonaws.com/prod/critical-thinking"
