AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Website for codetools-cheatsheets
Parameters:
  DomainName:
    Type: String
    Description: The custom domain name for the website
  BucketName:
    Type: String
    Description: The name of the S3 bucket where the website's files will be stored
  AcmCertificateArn:
    Type: String
    Description: The ARN of the ACM certificate for the custom domain

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: 
              - "s3:GetObject"
            Resource: 
              - !Sub "arn:aws:s3:::${Bucket}/*"

  CloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !Ref DomainName
        Origins:
          - DomainName: !GetAtt Bucket.DomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2018

Outputs:
  BucketName:
    Description: "The name of the website S3 bucket"
    Value: !Ref Bucket
    Export:
      Name: BucketName

  WebsiteURL:
    Description: "URL of the S3 bucket hosting the codetools-cheatsheets website"
    Value: !GetAtt Bucket.WebsiteURL

  CloudFrontDistributionDomainName:
    Description: "Domain name of the CloudFront distribution for codetools-cheatsheets"
    Value: !GetAtt CloudFront.DomainName
